### PR TITLE
Integrating Tesseract OCR into SWT demo

### PR DESCRIPTION
**Pull request by kostasx**

### CODE REVIEW

**Comment by fta2012** [comment]
Hey I tried out your OCR demo at https://kostasx.github.io/ccv-js/ and it's pretty cool.

I actually had very similar code that was in the SWT demo itself but I ended up removing it. The reason was because I also wanted to support live webcam (which works today if you change source to "WEBCAM") but tesseract.js consistently crashes the tab if you don't manage the promises you fire off for each frame. 

Working around this added some complexity and didn't work well (queuing up promises that you can't cancel, tracking which tesseract job corresponds with the current frame, but still permanently lagging behind because it can't process frames faster than they are coming, etc etc). So I removed it to focus on demoing the ccv stuff even though swt does work nicely with tesseract.js.

I probably don't want to merge this for that same reason. Thanks for the interest though!

**Comment by kostasx** [comment]
Fair enough. 
Amazing library by the way.

**Comment by fta2012** [comment]
Actually I thought about it some more and there's no reason why I can't just disable tesseract for videos. I made a [change](https://github.com/fta2012/ccv-js/commit/d35b57bb178f9cc8f2a45341e30ebad4ec061636) that's largely based on yours (including using your imgur image!). The demo should now be updated.

Thanks!

**Comment by kostasx** [comment]
👍 
That Aha moment when you realize that you've been trying too hard to stick with vanilla JS, and as a result you forget about all these jQuery gems like $.getScript. What was I thinking? :)

**Pull request closed without merging**
